"""empty message

Revision ID: 6c9b69973a11
Revises: 9dc84aecde2e
Create Date: 2024-07-04 09:35:18.828846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9b69973a11'
down_revision = '9dc84aecde2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adm', sa.Boolean(), nullable=True))
        batch_op.drop_column('cep')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('adm')

    op.create_table('endereco',
    sa.Column('id_endereco', sa.INTEGER(), nullable=False),
    sa.Column('cep', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id_endereco')
    )
    # ### end Alembic commands ###
