"""empty message

Revision ID: 8c1fe7d44bc5
Revises: c678a90212e2
Create Date: 2024-07-04 11:56:30.503194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1fe7d44bc5'
down_revision = 'c678a90212e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.alter_column('especial',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.alter_column('especial',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
