"""empty message

Revision ID: 9dc84aecde2e
Revises: c4494463fa0f
Create Date: 2024-07-04 09:09:42.742537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc84aecde2e'
down_revision = 'c4494463fa0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especial', sa.Boolean(), nullable=False))
        batch_op.alter_column('qntdestoque',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('avaliacao',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.alter_column('avaliacao',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('qntdestoque',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('especial')

    # ### end Alembic commands ###
