"""empty message

Revision ID: c0ec18756315
Revises: 6c9b69973a11
Create Date: 2024-07-04 10:40:57.683363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ec18756315'
down_revision = '6c9b69973a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('celestianus',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('celestianus',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
