"""empty message

Revision ID: c678a90212e2
Revises: 69dd82636a6c
Create Date: 2024-07-04 11:26:07.123031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c678a90212e2'
down_revision = '69dd82636a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(), nullable=False))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###
